// Code generated by goagen v1.2.0-dirty, DO NOT EDIT.
//
// API "Sample": Application User Types
//
// Command:
// $ goagen
// --design=github.com/tikasan/goa-code-reading/design
// --out=$(GOPATH)/src/github.com/tikasan/goa-code-reading
// --version=v1.2.0-dirty

package client
