consumes:
- application/json
- application/xml
- application/gob
- application/x-gob
definitions:
  POSTSamplePayload:
    example:
      defaultType: でふぉ
      email: example@gmail.com
      enumType: A
      integerType: 5
      reg: 12abc
      stringType: あいうえお
    properties:
      defaultType:
        description: デフォルト値
        example: でふぉ
        type: string
      email:
        description: メールアドレス
        example: example@gmail.com
        type: string
      enumType:
        description: 列挙型
        example: A
        type: string
      integerType:
        description: 数字（1〜10）
        example: 5
        format: int64
        type: integer
      reg:
        description: デフォルト値
        example: 12abc
        type: string
      stringType:
        description: 文字（1~10文字）
        example: あいうえお
        type: string
    required:
    - integerType
    - stringType
    - email
    - enumType
    - defaultType
    - reg
    title: POSTSamplePayload
    type: object
  Sample:
    description: example (default view)
    example:
      defaultType: でふぉ
      email: example@gmail.com
      enumType: A
      id: 1
      integerType: 5
      reg: 12abc
      stringType: あいうえお
    properties:
      defaultType:
        description: デフォルト値
        example: でふぉ
        type: string
      email:
        description: メールアドレス
        example: example@gmail.com
        type: string
      enumType:
        description: 列挙型
        example: A
        type: string
      id:
        description: id
        example: 1
        format: int64
        type: integer
      integerType:
        description: 数字（1〜10）
        example: 5
        format: int64
        type: integer
      reg:
        description: デフォルト値
        example: 12abc
        type: string
      stringType:
        description: 文字（1~10文字）
        example: あいうえお
        type: string
    required:
    - id
    - integerType
    - stringType
    - email
    - enumType
    - defaultType
    - reg
    title: 'Mediatype identifier: application/vnd.sample+json; view=default'
    type: object
  SampleCollection:
    description: SampleCollection is the media type for an array of Sample (default
      view)
    example:
    - defaultType: でふぉ
      email: example@gmail.com
      enumType: A
      id: 1
      integerType: 5
      reg: 12abc
      stringType: あいうえお
    - defaultType: でふぉ
      email: example@gmail.com
      enumType: A
      id: 1
      integerType: 5
      reg: 12abc
      stringType: あいうえお
    items:
      $ref: '#/definitions/Sample'
    title: 'Mediatype identifier: application/vnd.sample+json; type=collection; view=default'
    type: array
  error:
    description: Error response media type (default view)
    example:
      code: invalid_value
      detail: Value of ID must be an integer
      id: 3F1FKVRR
      meta:
        timestamp: 1.458609e+09
      status: "400"
    properties:
      code:
        description: an application-specific error code, expressed as a string value.
        example: invalid_value
        type: string
      detail:
        description: a human-readable explanation specific to this occurrence of the
          problem.
        example: Value of ID must be an integer
        type: string
      id:
        description: a unique identifier for this particular occurrence of the problem.
        example: 3F1FKVRR
        type: string
      meta:
        additionalProperties: true
        description: a meta object containing non-standard meta-information about
          the error.
        example:
          timestamp: 1.458609e+09
        type: object
      status:
        description: the HTTP status code applicable to this problem, expressed as
          a string value.
        example: "400"
        type: string
    title: 'Mediatype identifier: application/vnd.goa.error; view=default'
    type: object
host: localhost:8080
info:
  description: Sample
  title: Sample
  version: ""
paths:
  /:
    get:
      description: Sample
      operationId: Sample#GET
      parameters:
      - description: デフォルト値
        in: query
        name: defaultType
        required: true
        type: string
      - description: メールアドレス
        in: query
        name: email
        required: true
        type: string
      - description: 列挙型
        in: query
        name: enumType
        required: true
        type: string
      - description: id
        in: query
        name: id
        required: true
        type: integer
      - description: 数字（1〜10）
        in: query
        name: integerType
        required: true
        type: integer
      - description: デフォルト値
        in: query
        name: reg
        required: true
        type: string
      - description: 文字（1~10文字）
        in: query
        name: stringType
        required: true
        type: string
      produces:
      - application/vnd.goa.error
      - application/vnd.goa.error
      - application/vnd.sample+json; type=collection
      - application/vnd.goa.error
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/SampleCollection'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/error'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/error'
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/error'
      schemes:
      - http
      summary: GET Sample
      tags:
      - Sample
  /{id}:
    post:
      description: Sample
      operationId: Sample#POST
      parameters:
      - description: id
        in: path
        name: id
        required: true
        type: integer
      - in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/POSTSamplePayload'
      produces:
      - application/vnd.goa.error
      - application/vnd.goa.error
      - application/vnd.sample+json
      - application/vnd.goa.error
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/Sample'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/error'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/error'
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/error'
      schemes:
      - http
      summary: POST Sample
      tags:
      - Sample
  /swagger.json:
    get:
      operationId: swagger#/swagger.json
      responses:
        "200":
          description: File downloaded
          schema:
            type: file
      schemes:
      - http
      summary: Download swagger/swagger.json
  /swagger/{filepath}:
    get:
      operationId: swagger#/swagger/*filepath
      parameters:
      - description: Relative file path
        in: path
        name: filepath
        required: true
        type: string
      responses:
        "200":
          description: File downloaded
          schema:
            type: file
        "404":
          description: File not found
          schema:
            $ref: '#/definitions/error'
      schemes:
      - http
      summary: Download public/swagger/
produces:
- application/json
- application/xml
- application/gob
- application/x-gob
responses:
  NotFound:
    description: Not Found
  OK:
    description: OK
    schema:
      $ref: '#/definitions/Sample'
schemes:
- http
swagger: "2.0"
